# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

global_vars:
  - name: today
    type: date
    params:
      format: "%Y-%m-%d"


matches:
  # Simple text replacement
  - trigger: ";espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # And much more! For more information, visit the docs: https://espanso.org/docs/
  - trigger: ";lvf"
    replace: "Lucas Vieites"
  - trigger: ";lvb"
    replace: "lucas.vieitesfarina@booking.com"
  - trigger: ";lvr"
    replace: "[{{today}}] Lucas Vieites"

  - trigger: ";sn"
    replace: "ServiceNow"

  - trigger: ";oob"
    replace: "out-of-box"

  - trigger: ";euro"
    replace: "\u20ac"

  - trigger: ";dlps"
    replace: "Destination LPS"
